port: 7890
socks-port: 7891
mixed-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
dns:
  enabled: true
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - 119.29.29.29
    - 223.5.5.5
      #- 119.29.29.29
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1
    - tls://1.0.0.1:853
    - tls://dns.google:853
      #- tls://1.1.1.1:853
      #- tls://1.0.0.1:853
      #- 101.6.6.6:5353
  ipv6: true
  #enhanced-mode: fake-ip #redir-host
  #fake-ip-range: 198.18.0.1/16
  #fake-ip-filter:
  #  - '*.lan'
  #  - localhost.ptlogin2.qq.com
  use-hosts: true

  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.cloudflare.com'

hosts:
  '*.clash.dev': 127.0.0.1
  'alpha.clash.dev': '::1'
  #test.com: [1.1.1.1, 2.2.2.2]
  #search.com: google.com
  #clash.lan: clash
  clayton.eu.or: 10.144.84.198
  jiahe.eu.or: 10.144.100.6
  'qnap': 10.144.84.198
  'raspi': 10.144.100.6
  'hp': 10.144.176.30

# Clash for Windows
cfw-bypass:
  # 直连列表
  # MyList
  - qq.com
  - music.163.com
  - "*.13th.tech"
  - "*.423down.com"
  - "*.chaipip.com"
  - "*.chinaplay.store"
  - "*.hrtsea.com"
  - "*.kaikeba.com"
  - "*.laomo.me"
  - "*.mpyit.com"
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - "*.qupu123.com"
  - "*.pdfwifi.com"
  - "*.zhenguanyu.biz"
  - "*.zhenguanyu.com"
  - "*.snapdrop.net"
  # CN域名直连(中国|公司|网络)
  - "*.xn--fiqs8s"
  - "*.xn--55qx5d"
  - "*.xn--io0a7i"
  # 中国国内常见域名关键词直连
  - "*360buy*"
  - "*appzapp*"
  # 360
  - "*.dhrest.com"
  - "*.qhres.com"
  - "*.qhstatic.com"
  # 4399
  - "*.4399pk.com"
  - "*.img4399.com"
  # Alibaba
  - "*.aliapp.org"
  - "*.alibabacloud.com"
  - "*.alibabausercontent.com"
  - "*.alicloudccp.com"
  - "*.aliexpress.com"
  - "*.aliimg.com"
  - "*.alipay.com"
  - "*.alipayobjects.com"
  - "*.alisoft.com"
  - "*.aliyuncdn.com"
  - "*.aliyundrive.com"
  - "*.autonavi.com"
  - "*.dingtalk.com"
  - "*.hichina.com"
  - "*.mxhichina.com"
  - "*.soku.com"
  - "*.tbcache.com"
  - "*.tbcdn.com"
  - "*.tmall.com"
  - "*.tmall.hk"
  - "*.xiami.com"
  - "*.xiami.net"
  # Baidu
  - "*.baidubcr.com"
  - "*.baidupcs.com"
  - "*.baidustatic.com"
  - "*.bdurl.net"
  - "*.jomodns.com"
  # Bilibili
  - "*.acg.tv"
  - "*.acgvideo.com"
  - "*.b23.tv"
  - "*.bigfun.cn"
  - "*.bigfunapp.cn"
  - "*.biliapi.com"
  - "*.biliapi.net"
  - "*.biligame.com"
  - "*.biligame.net"
  - "*.bilivideo.com"
  - "*.bilivideo.cn"
  - "*.hdslb.com"
  - "*.im9.com"
  - "*.smtcdns.net"
  # ByteDance
  - "*.amemv.com"
  - "*.bdxiguaimg.com"
  - "*.bdxiguastatic.com"
  - "*.byted-static.com"
  - "*.bytedns.net"
  - "*.bytednsdoc.com"
  - "*.bytegoofy.com"
  - "*.byteimg.com"
  - "*.bytescm.com"
  - "*.bytetos.com"
  - "*.bytexservice.com"
  - "*.douyin.com"
  - "*.douyincdn.com"
  - "*.douyinpic.com"
  - "*.douyinstatic.com"
  - "*.douyinvod.com"
  - "*.feelgood.cn"
  - "*.feiliao.com"
  - "*.gifshow.com"
  - "*.huoshan.com"
  - "*.huoshanzhibo.com"
  - "*.ibytedapm.com"
  - "*.iesdouyin.com"
  - "*.ixigua.com"
  - "*.kspkg.com"
  - "*.toutiao13.com"
  - "*.toutiaoapi.com"
  - "*.toutiaocdn.com"
  - "*.toutiaocdn.net"
  - "*.toutiaocloud.com"
  - "*.toutiaohao.com"
  - "*.toutiaohao.net"
  - "*.toutiaoimg.com"
  - "*.toutiaopage.com"
  - "*.wukong.com"
  - "*.zijieapi.com"
  - "*.zijieimg.com"
  - "*.zjbyte.com"
  - "*.zjcdn.com"
  # CCTV
  - "*.cctvpic.com"
  - "*.livechina.com"
  # DiDi
  - "*.didialift.com"
  - "*.didiglobal.com"
  - "*.udache.com"
  # Douyu 斗鱼
  - "*.douyuscdn.com"
  # Epic
  - "*.epicgames.com"
  - "*.epicgames.dev"
  - "*.helpshift.com"
  - "*.paragon.com"
  - "*.unrealengine.com"
  # HuaWei
  - "*.dbankcdn.com"
  - "*.hc-cdn.com"
  - "*.hicloud.com"
  - "*.hihonor.com"
  - "*.huawei.com"
  - "*.huaweicloud.com"
  - "*.huaweishop.net"
  - "*.hwccpc.com"
  - "*.vmallres.com"
  # Heytap
  - "*.allawnfs.com"
  - "*.allawno.com"
  - "*.allawntech.com"
  - "*.coloros.com"
  - "*.heytap.com"
  - "*.heytapcs.com"
  - "*.heytapdownload.com"
  - "*.heytapimage.com"
  - "*.heytapmobi.com"
  - "*.oppoer.me"
  # Iflytek 科大讯飞
  - "*.iflyink.com"
  - "*.iflyrec.com"
  - "*.iflytek.com"
  # Iqiyi
  - "*.71edge.com"
  - "*.iqiyipic.com"
  - "*.ppsimg.com"
  - "*.qiyipic.com"
  - "*.qy.net"
  # JD
  - "*.360buyimg.com"
  - "*.jcloudcs.com"
  - "*.jdcloud.com"
  - "*.jdpay.com"
  - "*.paipai.com"
  # Kuaishou 快手
  - "*.yximgs.com"
  # Meitu
  - "*.meipai.com"
  # LeTV 乐视
  - "*.lecloud.com"
  - "*.letvcloud.com"
  - "*.letvimg.com"
  # MGTV 芒果TV
  - "*.hitv.com"
  # NetEase
  - "*.lofter.com"
  # PDD 拼多多
  - "*.pinduoduo.com"
  - "*.yangkeduo.com"
  # Sina
  - "*.miaopai.com"
  - "*.xiaoka.tv"
  # Sohu Sogo
  - "*.go2map.com"
  - "*.sogo.com"
  - "*.sohucs.com"
  - "*.sohuno.com"
  - "*.sohurdc.com"
  # Sony
  - "*.playstation.com"
  - "*.playstation.net"
  - "*.playstationnetwork.com"
  - "*.sony.com"
  - "*.sonyentertainmentnetwork.com"
  # SteamCN
  - "*.cm.steampowered.com"
  - "*.steamcontent.com"
  - "*.steamusercontent.com"
  - "*.steamchina.com"
  - "csgo.wmsj.cn"
  - "dota2.wmsj.cn"
  - "wmsjsteam.com"
  - "dl.steam.clngaa.com"
  - "dl.steam.ksyna.com"
  - "st.dl.bscstorage.net"
  - "st.dl.eccdnx.com"
  - "st.dl.pinyuncloud.com"
  - "xz.pphimalayanrt.com"
  - "steampipe.steamcontent.tnkjmec.com"
  - "steampowered.com.8686c.com"
  - "steamstatic.com.8686c.com"
  # Tencent
  - "*.foxmail.com"
  - "*.idqqimg.com"
  - "*.igamecj.com"
  - "*.myapp.com"
  - "*.qqmail.com"
  - "*.qqurl.com"
  - "*.smtcdns.com"
  - "*.smtcdns.net"
  - "*.soso.com"
  - "*.tencent-cloud.net"
  - "*.tencent.com"
  - "*.tenpay.com"
  - "*.wechat.com"
  - "*.weixin.com"
  - "*.weiyun.com"
  # Vip 唯品会
  - "*.appsimg.com"
  - "*.appvipshop.com"
  # Ximalaya 喜马拉雅
  - "*.xmcdn.com"
  # Xunlei 迅雷
  - "*.00cdn.com"
  - "*.88cdn.com"
  - "*.kanimg.com"
  - "*.p2cdn.com"
  - "*.thundercdn.com"
  # YYeTs 人人影视
  - "*.got001.com"
  - "*.p4pfile.com"
  - "*.rrys.tv"
  - "*.rrys2020.com"
  - "*.yyets.com"
  - "*.zimuzu.io"
  - "*.zimuzu.tv"
  - "*.zmz001.com"
  - "*.zmz002.com"
  - "*.zmz003.com"
  - "*.zmz004.com"
  - "*.zmz2019.com"
  - "*.zmzapi.com"
  - "*.zmzapi.net"
  - "*.zmzfile.com"
  # TeamViewer
  - "*.teamviewer.com"
  # Public Direct CDN 公共直连
  - "*.baomitu.com"
  - "*.bootcss.com"
  - "*.jiasule.com"
  - "*.staticfile.org"
  # China DNS
  - "*.doh.pub"
  - "*.dns.alidns.com"
  - "*.doh.360.cn"
  # AccelerateDirectSites
  - "*.36kr.com"
  - "*.3dmgame.com"
  - "*.51job.com"
  - "*.51jobcdn.com"
  - "*.8686c.com"
  - "*.abchina.com"
  - "*.abercrombie.com"
  - "*.acfun.tv"
  - "*.aixifan.com"
  - "*.algocasts.io"
  - "*.babytreeimg.com"
  - "*.baidupan.com"
  - "*.biqudu.com"
  - "*.c-ctrip.com"
  - "*.camera360.com"
  - "*.cdnmama.com"
  - "*.chaoxing.com"
  - "*.che168.com"
  - "*.chinacache.net"
  - "*.chuimg.com"
  - "*.cloudxns.net"
  - "*.cn163.net"
  - "*.cnblogs.com"
  - "*.cnki.net"
  - "*.cnmstl.net"
  - "*.coolapk.com"
  - "*.coolapkmarket.com"
  - "*.ctrip.com"
  - "*.dfcfw.com"
  - "*.dianping.com"
  - "*.dilidili.wang"
  - "*.dpfile.com"
  - "*.dxycdn.com"
  - "*.dytt8.net"
  - "*.ecitic.com"
  - "*.element-plus.org"
  - "*.ewqcxz.com"
  - "*.fantasy.tv"
  - "*.fengkongcloud.com"
  - "*.fir.im"
  - "*.frdic.com"
  - "*.fresh-ideas.cc"
  - "*.ganjistatic1.com"
  - "*.geetest.com"
  - "*.geilicdn.com"
  - "*.ghpym.com"
  - "*.godic.net"
  - "*.guazi.com"
  - "*.gzlzfm.com"
  - "*.haibian.com"
  - "*.hollisterco.com"
  - "*.hongxiu.com"
  - "*.huxiucdn.com"
  - "*.images-amazon.com"
  - "*.ipip.net"
  - "*.ithome.com"
  - "*.ixdzs.com"
  - "*.jianguoyun.com"
  - "*.jianshu.com"
  - "*.jianshu.io"
  - "*.jianshuapi.com"
  - "*.jmstatic.com"
  - "*.jumei.com"
  - "*.kaola.com"
  - "*.knewone.com"
  - "*.ksyungslb.com"
  - "*.kuaidi100.com"
  - "*.lancdns.com"
  - "*.landiannews.com"
  - "*.lanzou.com"
  - "*.lanzoui.com"
  - "*.lanzoux.com"
  - "*.lemicp.com"
  - "*.letitfly.me"
  - "*.lizhi.fm"
  - "*.lizhi.io"
  - "*.lizhifm.com"
  - "*.luoo.net"
  - "*.lvmama.com"
  - "*.lxdns.com"
  - "*.maoyan.com"
  - "*.meilishuo.com"
  - "*.migucloud.com"
  - "*.miguvideo.com"
  - "*.mogu.com"
  - "*.mogucdn.com"
  - "*.moke.com"
  - "*.msstatic.com"
  - "*.mubu.com"
  - "*.myunlu.com"
  - "*.nruan.com"
  - "*.nuomi.com"
  - "*.onedns.net"
  - "*.oneplus.com"
  - "*.onlinedown.net"
  - "*.oracle.com"
  - "*.oschina.net"
  - "*.ourdvs.com"
  - "*.polyv.net"
  - "*.qcloud.com"
  - "*.qcloudcdn.com"
  - "*.qdaily.com"
  - "*.qdmm.com"
  - "*.qianqian.com"
  - "*.qihucdn.com"
  - "*.qin.io"
  - "*.qiniu.com"
  - "*.qiniucdn.com"
  - "*.qiniudn.com"
  - "*.quanmin.tv"
  - "*.qunarzz.com"
  - "*.repaik.com"
  - "*.runoob.com"
  - "*.sankuai.com"
  - "*.segmentfault.com"
  - "*.sf-express.com"
  - "*.shumilou.net"
  - "*.simplecd.me"
  - "*.snwx.com"
  - "*.soufunimg.com"
  - "*.sspai.com"
  - "*.startssl.com"
  - "*.synology.com"
  - "*.taihe.com"
  - "*.th-sjy.com"
  - "*.tianqi.com"
  - "*.tianqistatic.com"
  - "*.tianyancha.com"
  - "*.tietuku.com"
  - "*.tmiaoo.com"
  - "*.trip.com"
  - "*.ttmeiju.com"
  - "*.tuniu.com"
  - "*.tuniucdn.com"
  - "*.upyun.com"
  - "*.uxengine.net"
  - "*.weico.cc"
  - "*.weidian.com"
  - "*.womai.com"
  - "*.wscdns.com"
  - "*.xhscdn.com"
  - "*.xinhuanet.com"
  - "*.xip.io"
  - "*.xiumi.us"
  - "*.xslb.net"
  - "*.xueqiu.com"
  - "*.yach.me"
  - "*.yeepay.com"
  - "*.yihaodianimg.com"
  - "*.yinxiang.com"
  - "*.yixia.com"
  - "*.ys168.com"
  - "*.yystatic.com"
  - "*.zealer.com"
  - "*.zhangzishi.cc"
  - "*.zhanqi.tv"
  - "*.zhaopin.com"
  - "*.zhimg.com"
  - "*.zhuihd.com"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 3000
proxy:
  - name: "ProxyH" # 默认使用的出站代理名称
    type: socks5 # 出站代理类型，支持 HTTP、HTTPS、SOCKS4 和 SOCKS5。

proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - 🎯 全球直连
      - ♻️ 自动选择
      - ⚡ 负载均衡
      - 🔰 manual
      - William_group
      - cflare
      - CFWarp
  - name: cflare
    type: url-test
    use:
      - cldflare
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
  - name: ♻️ 自动选择
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
    use:
      - common
  - name: 全局选择
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🛑 全球拦截
      - 🐟 漏网之鱼
      - 🎏 失败切换
      - ⚡ 负载均衡
  - name: 📲 电报信息
    type: select
    proxies:
      - 🎯 全球直连
      - ♻️ 自动选择
      - 🚀 节点选择
      - ⚡ 负载均衡
  - name: 🔰 manual
    type: select
    use:
      - common
      - cldflare
  - name: CFWarp
    type: url-test
    use:
      - cf-warp
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
  - name: William_group
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
    filter: "WilliamStar|NoMoreWalls" #(?i) (?A) 等语法无效
    #exclude-filter: "(?i)Flik" #无效
    use:
      - common
  - name: ⚡ 负载均衡
    type: load-balance
    use:
      - common
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
    strategy: consistent-hashing # or round-robin
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
  - name: 🎏 失败切换
    type: fallback
    use:
      - common
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
    use:
      - common
  - name: 🌏 国内媒体
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
    use:
      - common
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
      - ♻️ 自动选择
  - name: 🎥 NETFLIX
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
  - name: ⛔️ 广告拦截
    type: select
    proxies:
      - 🛑 全球拦截
      - 🎯 全球直连
      - 🚀 节点选择
  - name: 🚫 运营劫持
    type: select
    proxies:
      - 🛑 全球拦截
      - 🎯 全球直连
      - 🚀 节点选择

  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择

proxy-providers:
  common:
    url: "https://jiahe.eu.org:15443/clash_proxy/common_proxies.yaml"
    #exclude-type: "Shadowsocks|Http"
    #exclude-filter: "(?i)港|hk|hongkong|hong kong"
    #filter: "(?i)港|hk|hongkong|hong kong"
    type: http
    #type: file
    interval: 3600
    path: local_data/common-proxies.yaml
    health-check:
      enable: true
      interval: 1200
      url: 'http://www.gstatic.com/generate_204'
  cf-warp:
    type: http
    #type: file
    url: "https://jiahe.eu.org:15443/clash_proxy/warp-proxies.yaml"
    interval: 86411
    path: local_data/warp-proxies.yaml
    health-check:
      enable: true
      interval: 1200
      url: 'http://www.gstatic.com/generate_204'
  cldflare:
    url: "https://jiahe.eu.org:15443/clash_proxy/cloudflare-proxies.yaml"
    type: http
    #type: file
    interval: 180807
    path: local_data/cloudflare-proxies.yaml
    health-check:
      enable: true
      interval: 1200
      url: 'http://www.gstatic.com/generate_204'
rule-providers:
  reject:
    type: http
    behavior: domain
    #url: from "https://github.com/Loyalsoldier/clash-rules/tree/release"
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  UnBan:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml"
    path: ./ruleset/UnBan.yaml
    interval: 86400
  BanAD:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
    path: ./ruleset/BanAD.yaml
    interval: 86400
  BanEasyList:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml"
    path: ./ruleset/BanEasyList.yaml
    interval: 86400
  BanEasyListChina:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml"
    path: ./ruleset/BanEasyListChina.yaml
    interval: 86400
  BanEasyPrivacy:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyPrivacy.yaml"
    path: ./ruleset/BanEasyPrivacy.yaml
    interval: 86400
  BanProgramAD:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
    path: ./ruleset/BanProgramAD.yaml
    interval: 86400

  artificial_direct:
    type: http
    behavior: domain
    #url: "https://jiahe.eu.org:15443/clash_verge/ruleset/manual_direct.yaml"
    url: "https://raw.githubusercontent.com/FGWong/clash_config/main/ruleset/manual_direct.yaml"
    path: ./ruleset/manual_direct.yaml
    interval: 86400

  artificial_proxy:
    type: http
    behavior: domain
    #url: "https://jiahe.eu.org:15443/clash_verge/ruleset/manual_proxy.yaml"
    url: "https://raw.githubusercontent.com/FGWong/clash_config/main/ruleset/manual_proxy.yaml"
    path: ./ruleset/manual_proxy.yaml
    interval: 86400

  classical_direct:
    behavior: "classical" # domain, ipcidr or classical (仅限 Clash Premium 内核)
    type: http # file
    format: 'yaml' # or 'text'
    url: "https://raw.githubusercontent.com/FGWong/clash_config/main/ruleset/classical_direct.yaml"
    #url: "https://jiahe.eu.org:15443/clash_verge/ruleset/classical_direct.yaml"
    path: ./ruleset/classical_direct.yaml
    interval: 86400

  classical_proxy:
    behavior: "classical" # domain, ipcidr or classical (仅限 Clash Premium 内核)
    type: http # file
    format: 'yaml' # or 'text'
    #url: "https://jiahe.eu.org:15443/clash_verge/ruleset/classical_proxy.yaml"
    url: "https://raw.githubusercontent.com/FGWong/clash_config/main/ruleset/classical_proxy.yaml"
    path: ./ruleset/classical_proxy.yaml
    interval: 86400

rules:
  - RULE-SET,applications,🎯 全球直连
  - RULE-SET,classical_direct,🎯 全球直连
  - RULE-SET,artificial_direct,🎯 全球直连
  - RULE-SET,UnBan,🎯 全球直连
  - RULE-SET,classical_proxy,🚀 节点选择
  - RULE-SET,artificial_proxy,🚀 节点选择

  - DOMAIN,clash.razord.top,🎯 全球直连
  - DOMAIN,yacd.haishan.me,🎯 全球直连

  - RULE-SET,private,🎯 全球直连
  - RULE-SET,reject,🛑 全球拦截
  - RULE-SET,BanAD,🛑 全球拦截
  - RULE-SET,BanEasyList,🛑 全球拦截
  - RULE-SET,BanEasyPrivacy,🛑 全球拦截
  - RULE-SET,BanProgramAD,🛑 全球拦截
  - RULE-SET,icloud,🎯 全球直连
  - RULE-SET,apple,🍎 苹果服务
  - RULE-SET,google,🚀 节点选择
  - RULE-SET,proxy,🚀 节点选择
  - RULE-SET,direct,🎯 全球直连
  - RULE-SET,lancidr,🎯 全球直连
  - RULE-SET,cncidr,🎯 全球直连
  - RULE-SET,telegramcidr,📲 电报信息
  - GEOIP,LAN,🎯 全球直连
  - GEOIP,CN,🎯 全球直连,no-resolve

  #- DOMAIN-KEYWORD,limetorrents.,🚀 节点选择
  #- DOMAIN-SUFFIX,,🚀 节点选择
  #- DST-PORT,34567,🎯 全球直连
  #- DST-PORT,45678,🎯 全球直连
  #- SRC-PORT,34567,🎯 全球直连
  #- SRC-PORT,45678,🎯 全球直连

  - MATCH,🐟 漏网之鱼
